import { createServer, type RequestListener, type Server } from "node:http";
import { afterEach, describe, expect, it } from "vitest";
import { OpenAiCompatibleEmbeddingProvider, validateEmbeddingBaseUrl } from "../src/providers/openai-compatible";
const servers: Server[] = [];
async function endpoint(handler: RequestListener): Promise<string> { const server = createServer(handler); servers.push(server); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); if (address === null || typeof address === "string") throw new Error("server address unavailable"); return `http://127.0.0.1:${String(address.port)}/v1`; }
afterEach(async () => Promise.all(servers.splice(0).map((server) => new Promise<void>((resolve) => server.close(() => resolve())))));
function provider(baseUrl: string) { return new OpenAiCompatibleEmbeddingProvider({ baseUrl, apiKey: "test-key", model: "test-model", dimensions: 3, headers: { "x-test": "yes" } }); }
describe("OpenAI-compatible embedding provider", () => {
  it("validates safe custom URLs", () => { expect(validateEmbeddingBaseUrl("http://127.0.0.1:1234/v1").pathname).toBe("/v1"); expect(() => validateEmbeddingBaseUrl("http://example.com/v1")).toThrow(/Plaintext/u); expect(() => validateEmbeddingBaseUrl("https://user@example.com/v1")).toThrow(); expect(() => validateEmbeddingBaseUrl("https://example.com/v1/")).toThrow(); });
  it("preserves batch indexes and order", async () => { const baseUrl = await endpoint((request, response) => { expect(request.url).toBe("/v1/embeddings"); expect(request.headers.authorization).toBe("Bearer test-key"); response.setHeader("content-type", "application/json"); response.end(JSON.stringify({ object: "list", model: "test-model", data: [{ index: 1, embedding: [0, 1, 0] }, { index: 0, embedding: [1, 0, 0] }], usage: { prompt_tokens: 2, total_tokens: 2 } })); }); await expect(provider(baseUrl).embed({ inputs: ["alpha", "beta"], timeoutMs: 1000 })).resolves.toMatchObject({ ok: true, value: { dimensions: 3, vectors: [[1, 0, 0], [0, 1, 0]] } }); });
  it.each([[401, false], [403, false], [408, true], [429, true], [500, true]])("classifies HTTP %i without retries", async (status, retryable) => { let calls = 0; const baseUrl = await endpoint((_request, response) => { calls += 1; response.statusCode = status; if (status === 429) response.setHeader("retry-after", "2"); response.end("private raw error"); }); const result = await provider(baseUrl).embed({ inputs: ["alpha"], timeoutMs: 1000 }); expect(result).toMatchObject({ ok: false, error: { code: `PROVIDER_HTTP_${String(status)}`, retryable } }); expect(calls).toBe(1); expect(JSON.stringify(result)).not.toContain("private raw"); });
  it.each(["duplicate", "missing", "dimension", "nan", "model", "malformed"])("rejects %s responses", async (kind) => { const base = { object: "list", model: "test-model", data: [{ index: 0, embedding: [1, 0, 0] }, { index: 1, embedding: [0, 1, 0] }] }; const payload: unknown = kind === "duplicate" ? { ...base, data: [base.data[0], base.data[0]] } : kind === "missing" ? { ...base, data: [base.data[0]] } : kind === "dimension" ? { ...base, data: [{ index: 0, embedding: [1] }, base.data[1]] } : kind === "nan" ? { ...base, data: [{ index: 0, embedding: [null, 0, 0] }, base.data[1]] } : kind === "model" ? { ...base, model: "wrong" } : "not-json"; const baseUrl = await endpoint((_request, response) => { response.setHeader("content-type", "application/json"); response.end(typeof payload === "string" ? payload : JSON.stringify(payload)); }); const result = await provider(baseUrl).embed({ inputs: ["alpha", "beta"], timeoutMs: 1000 }); expect(result.ok).toBe(false); });
  it("supports cancellation, timeout, network close, and input limits", async () => { const baseUrl = await endpoint((request) => { request.socket.destroy(); }); const network = await provider(baseUrl).embed({ inputs: ["alpha"], timeoutMs: 1000 }); expect(network).toMatchObject({ ok: false, error: { code: "PROVIDER_NETWORK_FAILURE" } }); const slowUrl = await endpoint(() => undefined); const timeout = await provider(slowUrl).embed({ inputs: ["alpha"], timeoutMs: 10 }); expect(timeout).toMatchObject({ ok: false, error: { code: "PROVIDER_TIMEOUT" } }); const controller = new AbortController(); controller.abort(); const cancelled = await provider(slowUrl).embed({ inputs: ["alpha"], timeoutMs: 1000, signal: controller.signal }); expect(cancelled).toMatchObject({ ok: false, error: { code: "OPERATION_CANCELLED" } }); await expect(provider(baseUrl).embed({ inputs: [], timeoutMs: 1000 })).resolves.toMatchObject({ ok: false, error: { code: "PROVIDER_INPUT_INVALID" } }); });
});
